server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

app:
  name: basic-game-arena
  version: 0.1.0-SNAPSHOT
  commit: ${COMMIT_SHA:unknown}
