apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "basic-game-arena.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "basic-game-arena.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "basic-game-arena.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "basic-game-arena.name" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /actuator/health/liveness,  port: 8080 }
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: COMMIT_SHA
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['app.git.commit']
