apiVersion: v1
kind: Service
metadata:
  name: {{ include "basic-game-arena.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "basic-game-arena.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "basic-game-arena.name" . }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
